language: php
php:
  - 7.1
  - hhvm-3.3
  - hhvm-3.18
sudo: required
install:
  - composer install --prefer-source --no-interaction --dev
script:
  composer dump-autoload; ./vendor/bin/phpunit -c phpunit.xml
notifications:
  on_success: never
  on_failure: always
git:
depth: 1
matrix:
  allow_failures:
  - php: hhvm-3.3
  - php: hhvm-3.18
