language: php
php:
  - 7.1
install:
  - composer install --prefer-source --no-interaction
script:
  composer dump-autoload; ./vendor/bin/phpunit -c phpunit.xml
notifications:
  on_success: never
  on_failure: always
git:
depth: 1
